### PR TITLE
Updates to basler_camera for synchronization, more robustness

### PR DESCRIPTION
**Pull request by lwan-zz**
I think a race condition between enumerating cameras through Pylon5 and searching for cameras results in not being able to find cameras. Added a little loop that keeps checking until a specified serial is found.

### CODE REVIEW

**Comment by jonbinney** [comment]
@lwan how does this package install the pylon library? Does it make you do it manually?

**Comment by lwan-zz** [comment]
@jonbinney 
Yeah, you need to install it manually. I can port over the (rosdep?) stuff from `pylon_camera` if you think that's a good idea.

**Comment by jonbinney** [comment]
No need to port the pylon library rosdep stuff over yet. Technically it should still work (the ansible stuff in our repo adds the rosdep source link, which gets downloaded from our fork of the other basler library on github). At some point I need to do some cleanup on the pylon library installation, but that can wait.

**Comment by jonbinney** [comment]
Could you add a  dependency on "libpylon-dev" and "libpylon" in the `package.xml`? That should cause rosdep to install it (it will still use the rosdep rule from the other repo, which is fine)

**Comment by jonbinney** [comment]
nevermind, I've merged it locally and added the dependencies. I'll push to a new iron-kinetic-devel branch.

**Comment by lwan-zz** [comment]
Ah oops! Got distracted I guess...

**Pull request closed without merging**
